version: "3"
services:
  rabbitmq:
    # There is a prebuilt RabbitMQ image; see
    # https://hub.docker.com/_/rabbitmq/ for details.
    # This variant is built on Alpine Linux (it's smaller) and includes
    # the management UI.
    image: 'rabbitmq:3.6-management-alpine'
    expose:
      - 5672
      - 15672
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  orig:
    image: patriktorn/orig:3a
    restart: on-failure
    command: bash -c "npm install && node index.js"
    build:
      dockerfile: Dockerfile
      context:  ./orig
    working_dir: /orig
    ports:
      - "4000:4000"
    volumes:
      - "./orig/:/orig/"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  imed:
    image: patriktorn/imed:3b
    restart: on-failure
    command: bash -c "npm install && node index.js"
    build: 
      dockerfile: Dockerfile
      context: ./imed
    working_dir: /imed
    ports:
      - "4001:4001"
    volumes:
      - "./imed/:/imed/"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  httpserv:
    image: patriktorn/httpserv:3b
    restart: on-failure
    command: bash -c "npm install && node index.js"
    build: 
      dockerfile: Dockerfile
      context: ./httpserv
    working_dir: /httpserv
    ports:
      - "8080:8080"
    volumes:
      - "./httpserv/:/httpserv/"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq